### PR TITLE
DEM: Add support for GDAL vsicurl, vsizip support and avoid segfaults with huge VRT datasets

### LINKED ISSUE #596: Support GDAL /vsicurl and /vsizip prefixes to DEM paths
## Desired behavior

Allow users to supply DEM data to Gazebo that is zipped, or DEM data to Gazebo that is remotely hosted. I would like all of the following able to be supplied to the `Load()` function:
* https://gdal.org/user/virtual_file_systems.html

## Alternatives considered

Preventing users from using anything except local raw DEM files and stuff in Fuel.

## Implementation suggestion

* GDAL can load zipped DEM if you add the `/vsizip` prefix to the path
* GDAL can load remotely hosted DEM if you add  `/vsicurl/<your_server_address>` to the path

Use case:
* As a drone user that relies on ArduPilot and grid_map_geo, I want Gazebo to use the same terrain data as my drone's flight controller and path planner.

Example files - these are all zipped DEM hosted on a server
* https://terrain.ardupilot.org/SRTM1/
* https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip

## Additional context

You can add the following code block to `Dem_TEST.cc` and observe gazebo fail to load the data.
1. Add the code block to the Dem_TEST.cc file: 
    ```c++
    TEST_F(DemTest, LargeVRT)
    {
      // Load a large VRT DEM (used by ArduPilot)
      common::Dem dem;
      EXPECT_EQ(dem.Load("/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt"), 0);
    }
    ```
1. Rebuild the repo
1.  Observe the failure
````
ryan@B650-970:~/Dev/gz_harmonic_ws/src/gz-common$ ./build/gz-common5/bin/UNIT_Dem_TEST 
Running main() from /home/ryan/Dev/gz_harmonic_ws/src/gz-common/test/gtest_vendor/src/gtest_main.cc
[==========] Running 13 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 13 tests from DemTest
<<<<<<<<<<<<<<<< OMITTED FOR BREVITY >>>>>>>>>>>>>>>>>>>>
[ RUN      ] DemTest.LargeVRT
[Err] [SystemPaths.cc:425] Unable to find file with URI [/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt]
[Err] [SystemPaths.cc:525] Could not resolve file [/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt]
[Err] [SystemPaths.cc:425] Unable to find file with URI [/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt]
[Err] [SystemPaths.cc:525] Could not resolve file [/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt]
[Err] [Dem.cc:115] Unable to find DEM file[/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt].
/home/ryan/Dev/gz_harmonic_ws/src/gz-common/geospatial/src/Dem_TEST.cc:291: Failure
Expected equality of these values:
  dem.Load("/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt")
    Which is: -1
  0
[  FAILED  ] DemTest.LargeVRT (0 ms)
[----------] 13 tests from DemTest (48 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 1 test suite ran. (48 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DemTest.LargeVRT

 1 FAILED TEST
```

That said, GDAL can load the path `/vsizip/home/ryan/Dev/gz_harmonic_ws/src/gz-common/test/data/ap_srtm1.zip` fine:
```
$ gdalinfo /vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt
<<<<<<<<<<<<<<<< OMITTED FOR BREVITY >>>>>>>>>>>>>>>>>>>>
       /vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/S84W179.hgt.zip/S84W179.hgt
       /vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/S84W180.hgt.zip/S84W180.hgt
Size is 1296001, 604801
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-180.000138888888898,84.000138888888884)
Pixel Size = (0.000277777777778,-0.000277777777778)
Corner Coordinates:
Upper Left  (-180.0001389,  84.0001389) (180d 0' 0.50"W, 84d 0' 0.50"N)
Lower Left  (-180.0001389, -84.0001389) (180d 0' 0.50"W, 84d 0' 0.50"S)
Upper Right ( 180.0001389,  84.0001389) (180d 0' 0.50"E, 84d 0' 0.50"N)
Lower Right ( 180.0001389, -84.0001389) (180d 0' 0.50"E, 84d 0' 0.50"S)
Center      (   0.0000000,  -0.0000000) (  0d 0' 0.00"E,  0d 0' 0.00"S)
Band 1 Block=128x128 Type=Int16, ColorInterp=Undefined
  NoData Value=-32768
```

Here's more info on the zip file:
```
$ unzip -l /home/ryan/Dev/gz_harmonic_ws/src/gz-common/test/data/ap_srtm1.zip
Archive:  /home/ryan/Dev/gz_harmonic_ws/src/gz-common/test/data/ap_srtm1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 11758320  2024-01-09 21:34   ap_srtm1.vrt
---------                     -------
 11758320                     1 file
 ```

## Long term

I want Gazebo to automatically load terrain wherever my drone flies and expose the necessary services to load more "tiles", move the origin, and not run out of memory. ArduPilot's ground station software of MAVProxy, QGroundControl, and Mission Planner all can do this today. When using Gazebo, the ROS aerial industry currently has to hard code a single DEM tile, and if the drone flies out of bounds of the tile, there is no capability to load new tiles in Gazebo. Being able to just give Gazebo a link to a terrain server and call it good would be awesome.

### PR DESCRIPTION
**Pull request by Ryanf55**
# 🎉 New feature

Closes #596

## Summary

1. Adds initial support to load super large DEM datasets by exposing an API to limit the size of the loaded DEM.
1. Adds an alternative way of loading datafiles that make use of features like `vsizip` and `vsicurl` that aren't true filepaths.
1. Adds a compiler warning for if you use new versions of GDAL, which will lose precision in the current implementation, and potentially misrepresent NoData values.
   * This could be taken out, but could be an issue instead. A printed warning could be ok.
1. Add a few asserts for safety to catch coding errors earlier
1. The user-configurable size limits can be used to prevent segmentation faults by loading too big of a raster dataset
1. FIxed overflow and segfault in RasterIO for massive DEM's and overflow risk in vector resize operations

## Test it

I added a unit test which is self explanatory.
```bash
./build/bin/UNIT_Dem_TEST
```

I also hacked a demo with one SRTMHGT file, and confirmed it can load. Gazebo does not perform well with this terrain size (3601 x 3601), but it does load. SDF needs ability to truncate the size of the heightmap in order to be usable, or perhaps decimate the data resolution.
image

## Open Questions

* How do we want the logs to look? Perhaps queue the errors and only report them if the DEM loading fails.
  
* Do we need to solve user-configurable origin to load? The previous implementation loaded everything in the raster, so there was nothing to configure
  * Not yet
* Should we rely on ArduPilot's terrain server being up for the test, or generate a large in-memory dataset for testing large rasters?
  *  No, we've relocated a large VRT locally to avoid dependence on an external resource

## Future Improvements

* File  an upstream GDAL bug about the segfault and ask for a recommendation how to prevent it: https://github.com/OSGeo/gdal/issues/9713
* Expose an API to let users change which part of the large DEM is initially loaded
* Expose an API to let users, after an inititial load, to re-load  more terrain to handle a drone flying very far
* 

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by Ryanf55** [comment]
@ahcorde Would you be able to provide another round of feedback on the functionality of this PR. I'm looking for some direction on how to best contribute my time to Gazebo's support of terrain data. We can use Gazebo for outdoor 3D aerial robotics applications that the aerial working group is currently working on.

File: geospatial/src/Dem_TEST.cc [hunk 1]
```diff
@@ -282,3 +282,22 @@ TEST_F(DemTest, LunarDemLoad)
...
 }
+
+TEST_F(DemTest, LargeVRTWithZipAndCurl)
+{
+  // Load a large VRT DEM from another server (used by ArduPilot).
+  common::Dem dem;
+  dem.SetXSizeLimit(100);
+  dem.SetYSizeLimit(50);
+  //! @todo Make a really large VRT locally
+  auto const res = dem.Load("/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt");
```
Comment (azeey) [inline geospatial/src/Dem_TEST.cc:293]: I don't think we should be accessing ardupilot.org from a test here. I'd rather avoid accessing the internet if possible, otherwise, maybe we can add something to Fuel?

**Review by azeey — CHANGES_REQUESTED** [review]

File: geospatial/src/Dem_TEST.cc (hunk 1 above)
Comment (Ryanf55) [reply geospatial/src/Dem_TEST.cc:293]: Can do

Comment (Ryanf55) [reply geospatial/src/Dem_TEST.cc:293]: Can you upload the following file into the Fuel for me? You can call it `S36E149.hgt.zip`. 

https://terrain.ardupilot.org/SRTM1/S36E149.hgt.zip
    
```bash
$ gdallocationinfo -wgs84 /vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/ap_srtm1.zip/ap_srtm1.vrt 149.165230 -35.363261
Report:
  Location: (1184995P,429708L)
  Band 1:
    <LocationInfo><File>/vsizip/vsicurl/https://terrain.ardupilot.org/SRTM1/S36E149.hgt.zip/S36E149.hgt</File></LocationInfo>
    Value: 587
```

Comment (Ryanf55) [reply geospatial/src/Dem_TEST.cc]: Done in c001ba176f7e199ee6276581e8c668ef8b5b4b2b. It works without internet. I added both a VRT and a VRT inside of a zipfile to test both the /vsizip and large VRT scenarios as part of the repo. It doesn't use Fuel.

File: geospatial/src/Dem.cc [hunk 2]
```diff
@@ -448,44 +494,68 @@ void Dem::FillHeightMap(int _subSampling, unsigned int _vertSize,
...
   }
 
-  // Read the whole raster data and convert it to a GDT_Float32 array.
-  // In this step the DEM is scaled to destWidth x destHeight
+  //! @todo In GDAL versions 3.5 or higher, where GDT_Int64 and GDT_UInt64 datasets were added,
+  // this logic will lose precision because it loads into a float.
+  // Additionally, the NoData value will not work.
+  //! @ref https://gdal.org/api/gdalrasterband_cpp.html#_CPPv4N14GDALRasterBand21GetNoDataValueAsInt64EPi
+  #if GDAL_VERSION_MINOR >= 5
+  #warning "DEM datasets with 64 bit height precision are not yet supported. Accuracy will be lost."
```
Comment (Ryanf55) [inline geospatial/src/Dem.cc:547]: Only give this warning at runtime if the dataset is 64 bit.

File: geospatial/src/Dem.cc [hunk 3]
```diff
@@ -448,44 +494,68 @@ void Dem::FillHeightMap(int _subSampling, unsigned int _vertSize,
...
+  #endif  // Read the whole raster data and convert it to a GDT_Float32 array.
+  // In this step the DEM is scaled to destWidth x destHeight.
+
   std::vector<float> buffer;
-  buffer.resize(destWidth * destHeight);
-  if (this->dataPtr->band->RasterIO(GF_Read, 0, 0, nXSize, nYSize, &buffer[0],
+  // Convert to uint64_t for multiplication to avoid overflow.
+  // https://github.com/OSGeo/gdal/issues/9713
+  static_assert(std::numeric_limits<uint64_t>::max() >= std::numeric_limits<uint32_t>::max() * std::numeric_limits<uint32_t>::max());
```
Comment (Ryanf55) [inline geospatial/src/Dem.cc:554]:
```suggestion
```

Comment (Ryanf55) [inline geospatial/src/Dem.cc:554]:
```suggestion
  static_assert(std::numeric_limits<uint64_t>::max() >= std::numeric_limits<int>::max() * std::numeric_limits<int>::max());
```

File: geospatial/src/Dem.cc (hunk 2 above)
Comment (Ryanf55) [reply geospatial/src/Dem.cc]: Cut out from this PR, will put it on another branch.

File: geospatial/src/Dem.cc [hunk 4]
```diff
@@ -110,21 +134,32 @@ int Dem::Load(const std::string &_filename)
 
   this->dataPtr->filename = fullName;
 
-  if (!exists(findFilePath(fullName)))
+  // Create a re-usable lambda for opening a dataset.
+  auto OpenInGdal = [this](const std::string& name) -> bool
```
Comment (azeey) [inline geospatial/src/Dem.cc:138]: nit: we normally treat lambdas as local variables, so first letter should be lower case.
```suggestion
  auto openInGdal = [this](const std::string& name) -> bool
```

File: geospatial/src/Dem.cc [hunk 5]
```diff
@@ -110,21 +134,32 @@ int Dem::Load(const std::string &_filename)
...
   {
-    gzerr << "Unable to find DEM file[" << _filename << "]." << std::endl;
-    return -1;
-  }
+    GDALDatasetH handle = GDALOpen(name.c_str(), GA_ReadOnly);
+    if (handle) {
+      this->dataPtr->dataSet = GDALDataset::FromHandle(handle);
+    }
```
Comment (azeey) [inline geospatial/src/Dem.cc:143]: nit
```suggestion
    if (handle)
    {
      this->dataPtr->dataSet = GDALDataset::FromHandle(handle);
    }
```

File: geospatial/src/Dem.cc [hunk 6]
```diff
@@ -110,21 +134,32 @@ int Dem::Load(const std::string &_filename)
...
-  if (!exists(findFilePath(fullName)))
+  // Create a re-usable lambda for opening a dataset.
+  auto OpenInGdal = [this](const std::string& name) -> bool
   {
-    gzerr << "Unable to find DEM file[" << _filename << "]." << std::endl;
-    return -1;
-  }
+    GDALDatasetH handle = GDALOpen(name.c_str(), GA_ReadOnly);
+    if (handle) {
+      this->dataPtr->dataSet = GDALDataset::FromHandle(handle);
```
Comment (azeey) [inline geospatial/src/Dem.cc:142]: Glad we can get rid of the `reinterpret_cast`. Can you do the same in the destructor?

File: geospatial/src/Dem_TEST.cc [hunk 7]
```diff
@@ -282,3 +282,34 @@ TEST_F(DemTest, LunarDemLoad)
...
+}
+
+TEST_F(DemTest, LargeVRTWithoutLimitsThrows)
+{
+  // Load a large VRT DEM without limits.
+  common::Dem dem;
+  auto const path = common::testing::TestFile("data", "ap_srtm1.vrt");
+  // We expect not to be able to allocate the data, so ensure we throw instead of segfault.
+  EXPECT_THROW(dem.Load(path), std::bad_alloc);
+}
```
Comment (azeey) [inline geospatial/src/Dem_TEST.cc:315]: nit: GitHub shows this file doesn't end in a new line. Can you fix that?

File: geospatial/src/Dem_TEST.cc [hunk 8]
```diff
@@ -282,3 +282,34 @@ TEST_F(DemTest, LunarDemLoad)
...
+  EXPECT_EQ(res, 0);
+}
+
+TEST_F(DemTest, LargeVRTWithoutLimitsThrows)
+{
+  // Load a large VRT DEM without limits.
+  common::Dem dem;
+  auto const path = common::testing::TestFile("data", "ap_srtm1.vrt");
+  // We expect not to be able to allocate the data, so ensure we throw instead of segfault.
+  EXPECT_THROW(dem.Load(path), std::bad_alloc);
```
Comment (azeey) [inline geospatial/src/Dem_TEST.cc:314]: Is this actually causing `Dem::Load` to allocate more memory than available? I'm not sure if we want to do this in a unit test if it might badly affect other things running on CI.

File: geospatial/src/Dem_TEST.cc [hunk 9]
```diff
@@ -282,3 +282,34 @@ TEST_F(DemTest, LunarDemLoad)
   EXPECT_NEAR(dem.WorldWidth(), 80.0417, 1e-2);
   EXPECT_NEAR(dem.WorldHeight(), 80.0417, 1e-2);
 }
+
+TEST_F(DemTest, LargeVRTWithLimits)
+{
+  // Load a large VRT DEM using GDAL but set limits on the size.
+  common::Dem dem;
+  dem.SetXSizeLimit(100);
+  dem.SetYSizeLimit(50);
```
Comment (azeey) [inline geospatial/src/Dem_TEST.cc:291]: It would be nice to verify these limits with getters.

**Review by azeey — COMMENTED** [review]
Looks great! Thanks for the contribution. I have a few comments, but they should all be easy to address.

**Comment by azeey** [comment]
Also, please merge from `gz-common5` to get the latest changes that fix CI failures.

**Comment by azeey** [comment]
@Ryanf55 we are now in Feature freeze for Gazebo Ionic. Since PR is already open, I've applied the `beta` label which means it's slotted for the Ionic release if we can get it merged before 08/28/2024. Do you think that's feasible? If not, please let me know and I'll remove the `beta` label.

**Comment by Ryanf55** [comment]
Thanks for the heads up, I'll do my best to make time over the next 2 days.

File: geospatial/src/Dem.cc (hunk 6 above)
Comment (Ryanf55) [reply geospatial/src/Dem.cc:163]: https://gdal.org/api/raster_c_api.html#_CPPv49GDALClose12GDALDatasetH
Yep! Added in 5e03fc3488c1416266e57db9b5e7bd7008eeec83.

**Review by Ryanf55 — COMMENTED** [review]
@azeey I've implemented all of your requests. This is ready for final approval, hopefully before the official release.

**Comment by Ryanf55** [comment]
> gz-common5

Rebase complete.

File: geospatial/src/Dem_TEST.cc (hunk 8 above)
Comment (azeey) [reply geospatial/src/Dem_TEST.cc:317]: CI is failing on macOS with a timeout so the behavior may not be the same on all platforms, so I'd prefer we use `GTEST_SKIP` as you suggested.

**Review by azeey — APPROVED** [review]
LGTM with green CI!
